name: Deploy EKS Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read Configuration File
      id: config
      run: |
        CONFIG_FILE=action-config.txt
        if [ -f "$CONFIG_FILE" ]; then
          source "$CONFIG_FILE"
          echo "::set-output name=action::$ACTION"
        else
          echo "Configuration file not found: $CONFIG_FILE"
          exit 1
        fi
      shell: bash
      

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.1 

    - name: Initialize Terraform
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Execute Terraform
      run: |
        if [[ "${{ steps.config.outputs.action }}" == "create" ]]; then
          terraform plan -var-file="ambientes/hom.tfvars" -out=plan
          terraform apply -auto-approve
        elif [[ "${{ steps.config.outputs.action }}" == "destroy" ]]; then
          terraform destroy -auto-approve
        else
          echo "Invalid action specified in configuration file."
          exit 1
        fi
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}